const express = require("express");
const Url = require("../models/url");
const { Authorization } = require("../middleware/auth");
const router = express.Router();

//route for admins
router.get("/admin/urls", Authorization(["ADMIN"]), async (req, res) => {
  const allUrls = await Url.find({}); //find all
  return res.render("home", { urls: allUrls });
});

//route for home page , which can be accessed by both, normal and admin
router.get("/", Authorization(["NORMAL", "ADMIN"]), async (req, res) => {
  const allUrls = await Url.find({ createdBy: req.user._id }); //show urls generated by curr user only
  return res.render("home", { urls: allUrls });
});

//to render signup page
router.get("/signup", (req, res) => {
  return res.render("signup");
});

//to render login page
router.get("/login", (req, res) => {
  return res.render("login");
});

module.exports = router;
