const shortid = require("shortid"); //npm to generate short url
const Url = require("../models/url");

async function handleShortUrl(req, res) {
  const body = req.body;
  if (!body.url) return res.status(400).json({ error: "Url required" });

  const shortUrl = shortid();

  await Url.create({
    shortUrl: shortUrl,     //generated by nanoid
    redirectUrl: body.url,  //entered by user
    viewHistory: [],
    createdBy: req.user._id,
  });

  return res.render("home", { id: shortUrl });
}

//find the id and count on total clicks made by returning length of viewhistory

async function handleGetAnalytics(req, res) {
  const shortUrl = req.params.shortUrl;
  const result = await Url.findOne({ shortUrl });

  return res.json({
    totalClicks: result.visitHistory.length,
    analytics: result.visitHistory,
  });
}

module.exports = {
  handleShortUrl,
  handleGetAnalytics,
};
